config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :restaurants, only: [:index, :show, :create, :new] do
    resources :reviews, only: [:create, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: %w[chinese italian japanese french belgian],
                                    message: '%{value} is not a valid category' }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :rating, :content, presence: true
  validates :rating, numericality: { only_integer: true, in: (0..5) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @review = Review.new
    # redirect_to restaurant_reviews_path(@restaurant)
  end

  def new
    @restaurant = Restaurant.new
    @review = Review.new
    @review.restaurant = @restaurant
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant), notice: "Review was succesfully posted"
    else
      render 'restaurants/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category, collection: %w[chinese italian japanese french belgian] %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/_list.html.erb
<div id="restaurants" class="mx-auto p-2 border my-2">
  <% restaurants.each do |restaurant| %>
    <%= render restaurant %>
    <p>
      <button class="btn border-primary m-3"><%= link_to "Show this restaurant", restaurant %></button>
    </p>
  <% end %>
</div>

app/views/restaurants/_restaurant.html.erb
<div id="<%= dom_id restaurant %>" class="border-top mx-auto p-3 my-2 d-flex justify-content-between">
  <div>
    <p>
      <strong>Name:</strong>
      <%= restaurant.name %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= restaurant.address %>
    </p>

    <p>
      <strong>Phone Number:</strong>
      <%= restaurant.phone_number %>
    </p>

    <p>
      <strong>Category:</strong>
      <%= restaurant.category %>
    </p>
  </div>
  <div style="width: 200px; height: 200px; background-image: URL(https://source.unsplash.com/random/?food); background-size:cover;">
  </div>

</div>

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Restaurants</h1>

<%= render "restaurants/list", restaurants: @restaurants %>
<button class="btn border-primary m-3"><%= link_to "New restaurant", new_restaurant_path %></button>

app/views/restaurants/new.html.erb
<h1>New restaurant</h1>

<%= render "form", restaurant: @restaurant %>

<br>

<div>
  <%= link_to "Back to restaurants", restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<%def stars(int)%>
  <%result = ""%>
  <%int.times do%>
    <%result += "⭐️"%>
  <%end%>
  <%result%>
<%end%>


<p style="color: green"><%= notice %></p>

<%= render @restaurant %>

<h1><strong>Reviews</strong></h1>
<h2>New Review</h2>

<div class="mx-5">
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, as: :range, input_html:{ min:"0", max:"5", oninput:"updateTextInput(this.value)"}%>
  <input type="text" id="textInput" value="">
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
</div>

<script>
function updateTextInput(val) {
          document.getElementById('textInput').value=val;
        }
</script>

<h2 class="mt-5">Reviews</h2>
<ul class="list-group">
  <% @restaurant.reviews.each do |review| %>
    <li class="list-group-item">
      <div class="row">
        <div class="col-1">
          <%= stars(review.rating)%>
        </div>
        <div class="col-11">
          <%= review.content%>
        </div>
      </div>
    </li>
  <% end %>
</ul>
<br>

<div>
  <button class="btn border-primary m-3"><%= link_to "Back to restaurants", restaurants_path %></button>
</div>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<div class="mx-5">
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :rating, as: :range, input_html:{ min:"0", max:"5", oninput:"updateTextInput(this.value)"}%>
  <input type="text" id="textInput" value="">
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>
</div>

<script>
function updateTextInput(val) {
          document.getElementById('textInput').value=val;
        }
</script>